// Round of 32 structure for the 2026 FIFA World Cup, per FIFA's published
// regulations (Annex C). Matches 73-88. Each match's "home"/"away" is
// either a direct group result (winner/runner-up) or a "third" slot whose
// actual team depends on which 8 of the 12 groups' third-place teams make
// the best-8 cut — resolved via ANNEX_C below, exactly as FIFA pre-defined
// it (so the bracket is fixed before anyone knows who actually qualifies).

// Full knockout structure for the 2026 FIFA World Cup: Matches 73-104.
// 73-88 = Round of 32, 89-96 = Round of 16, 97-100 = Quarterfinals,
// 101-102 = Semifinals, 103 = Third Place Match, 104 = Final.
//
// Round of 32 "home"/"away" are direct group results (winner/runner-up) or
// a "third" slot resolved via ANNEX_C below. Every later round references
// its two feeder matches by number ("winnerOf"/"loserOf") — since match
// numbers strictly increase round over round, resolving 73 -> 104 in order
// is enough; no recursion needed.

export const ROUND_LABELS = {
  R32: "Round of 32",
  R16: "Round of 16",
  QF: "Quarterfinals",
  SF: "Semifinals",
  "3RD": "Third Place Match",
  F: "Final",
};

export const ROUND_ORDER = ["R32", "R16", "QF", "SF", "F"];

export const KNOCKOUT_MATCHES = [
  // ---------- Round of 32 ----------
  { num: 73, round: "R32", date: "2026-06-28", time: "3:00 PM ET", venue: "SoFi Stadium, Inglewood", home: { type: "runnerup", group: "A" }, away: { type: "runnerup", group: "B" } },
  { num: 76, round: "R32", date: "2026-06-29", time: "1:00 PM ET", venue: "NRG Stadium, Houston", home: { type: "winner", group: "C" }, away: { type: "runnerup", group: "F" } },
  { num: 74, round: "R32", date: "2026-06-29", time: "4:30 PM ET", venue: "Gillette Stadium, Foxborough", home: { type: "winner", group: "E" }, away: { type: "third", slot: "E" } },
  { num: 75, round: "R32", date: "2026-06-29", time: "9:00 PM ET", venue: "Estadio BBVA, Monterrey", home: { type: "winner", group: "F" }, away: { type: "runnerup", group: "C" } },
  { num: 78, round: "R32", date: "2026-06-30", time: "1:00 PM ET", venue: "AT&T Stadium, Arlington", home: { type: "runnerup", group: "E" }, away: { type: "runnerup", group: "I" } },
  { num: 77, round: "R32", date: "2026-06-30", time: "5:00 PM ET", venue: "MetLife Stadium, East Rutherford", home: { type: "winner", group: "I" }, away: { type: "third", slot: "I" } },
  { num: 79, round: "R32", date: "2026-06-30", time: "9:00 PM ET", venue: "Estadio Azteca, Mexico City", home: { type: "winner", group: "A" }, away: { type: "third", slot: "A" } },
  { num: 80, round: "R32", date: "2026-07-01", time: "12:00 PM ET", venue: "Mercedes-Benz Stadium, Atlanta", home: { type: "winner", group: "L" }, away: { type: "third", slot: "L" } },
  { num: 82, round: "R32", date: "2026-07-01", time: "4:00 PM ET", venue: "Lumen Field, Seattle", home: { type: "winner", group: "G" }, away: { type: "third", slot: "G" } },
  { num: 81, round: "R32", date: "2026-07-01", time: "8:00 PM ET", venue: "Levi's Stadium, Santa Clara", home: { type: "winner", group: "D" }, away: { type: "third", slot: "D" } },
  { num: 84, round: "R32", date: "2026-07-02", time: "3:00 PM ET", venue: "SoFi Stadium, Inglewood", home: { type: "winner", group: "H" }, away: { type: "runnerup", group: "J" } },
  { num: 83, round: "R32", date: "2026-07-02", time: "7:00 PM ET", venue: "BMO Field, Toronto", home: { type: "runnerup", group: "K" }, away: { type: "runnerup", group: "L" } },
  { num: 85, round: "R32", date: "2026-07-02", time: "11:00 PM ET", venue: "BC Place, Vancouver", home: { type: "winner", group: "B" }, away: { type: "third", slot: "B" } },
  { num: 88, round: "R32", date: "2026-07-03", time: "2:00 PM ET", venue: "AT&T Stadium, Arlington", home: { type: "runnerup", group: "D" }, away: { type: "runnerup", group: "G" } },
  { num: 86, round: "R32", date: "2026-07-03", time: "6:00 PM ET", venue: "Hard Rock Stadium, Miami Gardens", home: { type: "winner", group: "J" }, away: { type: "runnerup", group: "H" } },
  { num: 87, round: "R32", date: "2026-07-03", time: "9:30 PM ET", venue: "Arrowhead Stadium, Kansas City", home: { type: "winner", group: "K" }, away: { type: "third", slot: "K" } },

  // ---------- Round of 16 ----------
  { num: 90, round: "R16", date: "2026-07-04", time: "1:00 PM ET", venue: "NRG Stadium, Houston", home: { type: "winnerOf", match: 73 }, away: { type: "winnerOf", match: 75 } },
  { num: 89, round: "R16", date: "2026-07-04", time: "5:00 PM ET", venue: "Lincoln Financial Field, Philadelphia", home: { type: "winnerOf", match: 74 }, away: { type: "winnerOf", match: 77 } },
  { num: 91, round: "R16", date: "2026-07-05", time: "4:00 PM ET", venue: "MetLife Stadium, East Rutherford", home: { type: "winnerOf", match: 76 }, away: { type: "winnerOf", match: 78 } },
  { num: 92, round: "R16", date: "2026-07-05", time: "8:00 PM ET", venue: "Estadio Azteca, Mexico City", home: { type: "winnerOf", match: 79 }, away: { type: "winnerOf", match: 80 } },
  { num: 93, round: "R16", date: "2026-07-06", time: "3:00 PM ET", venue: "AT&T Stadium, Arlington", home: { type: "winnerOf", match: 83 }, away: { type: "winnerOf", match: 84 } },
  { num: 94, round: "R16", date: "2026-07-06", time: "8:00 PM ET", venue: "Lumen Field, Seattle", home: { type: "winnerOf", match: 81 }, away: { type: "winnerOf", match: 82 } },
  { num: 95, round: "R16", date: "2026-07-07", time: "12:00 PM ET", venue: "Mercedes-Benz Stadium, Atlanta", home: { type: "winnerOf", match: 86 }, away: { type: "winnerOf", match: 88 } },
  { num: 96, round: "R16", date: "2026-07-07", time: "4:00 PM ET", venue: "BC Place, Vancouver", home: { type: "winnerOf", match: 85 }, away: { type: "winnerOf", match: 87 } },

  // ---------- Quarterfinals ----------
  { num: 97, round: "QF", date: "2026-07-09", time: "4:00 PM ET", venue: "Gillette Stadium, Foxborough", home: { type: "winnerOf", match: 89 }, away: { type: "winnerOf", match: 90 } },
  { num: 98, round: "QF", date: "2026-07-10", time: "3:00 PM ET", venue: "SoFi Stadium, Inglewood", home: { type: "winnerOf", match: 93 }, away: { type: "winnerOf", match: 94 } },
  { num: 99, round: "QF", date: "2026-07-11", time: "5:00 PM ET", venue: "Hard Rock Stadium, Miami Gardens", home: { type: "winnerOf", match: 91 }, away: { type: "winnerOf", match: 92 } },
  { num: 100, round: "QF", date: "2026-07-11", time: "9:00 PM ET", venue: "Arrowhead Stadium, Kansas City", home: { type: "winnerOf", match: 95 }, away: { type: "winnerOf", match: 96 } },

  // ---------- Semifinals ----------
  { num: 101, round: "SF", date: "2026-07-14", time: "3:00 PM ET", venue: "AT&T Stadium, Arlington", home: { type: "winnerOf", match: 97 }, away: { type: "winnerOf", match: 98 } },
  { num: 102, round: "SF", date: "2026-07-15", time: "3:00 PM ET", venue: "Mercedes-Benz Stadium, Atlanta", home: { type: "winnerOf", match: 99 }, away: { type: "winnerOf", match: 100 } },

  // ---------- Third Place Match & Final ----------
  { num: 103, round: "3RD", date: "2026-07-18", time: "5:00 PM ET", venue: "Hard Rock Stadium, Miami Gardens", home: { type: "loserOf", match: 101 }, away: { type: "loserOf", match: 102 } },
  { num: 104, round: "F", date: "2026-07-19", time: "3:00 PM ET", venue: "MetLife Stadium, East Rutherford", home: { type: "winnerOf", match: 101 }, away: { type: "winnerOf", match: 102 } },
];

// Which possible groups can feed each "third" slot (for display before the
// combination is resolved) — matches FIFA's published "Best 3rd Group X/Y/Z" labels.
export const THIRD_SLOT_CANDIDATES = {
  A: ["C", "E", "F", "H", "I"],
  B: ["E", "F", "G", "I", "J"],
  D: ["B", "E", "F", "I", "J"],
  E: ["A", "B", "C", "D", "F"],
  G: ["A", "E", "H", "I", "J"],
  I: ["C", "D", "F", "G", "H"],
  K: ["D", "E", "I", "J", "L"],
  L: ["E", "H", "I", "J", "K"],
};

// Column order used in the compact encoding below: A,B,D,E,G,I,K,L
const SLOT_COLS = ["A", "B", "D", "E", "G", "I", "K", "L"];

// All 495 possible combinations of "which 8 of the 12 groups produced a
// qualifying third-place team", each mapped to the resulting slot
// assignment. Format per line: "<8 sorted qualifying letters>:<8 assignment
// letters in SLOT_COLS order>". Sourced from FIFA's Annex C (via the
// regulations, as tabulated on Wikipedia) and parsed/validated to confirm
// all 495 rows are unique, internally consistent permutations.
const ANNEX_C_RAW = `EFGHIJKL:EJIFHGLK
DFGHIJKL:HGIDJFLK
DEGHIJKL:EJIDHGLK
DEFHIJKL:EJIDHFLK
DEFGIJKL:EGIDJFLK
DEFGHJKL:EGJDHFLK
DEFGHIKL:EGIDHFLK
DEFGHIJL:EGJDHFLI
DEFGHIJK:EGJDHFIK
CFGHIJKL:HGICJFLK
CEGHIJKL:EJICHGLK
CEFHIJKL:EJICHFLK
CEFGIJKL:EGICJFLK
CEFGHJKL:EGJCHFLK
CEFGHIKL:EGICHFLK
CEFGHIJL:EGJCHFLI
CEFGHIJK:EGJCHFIK
CDGHIJKL:HGICJDLK
CDFHIJKL:CJIDHFLK
CDFGIJKL:CGIDJFLK
CDFGHJKL:CGJDHFLK
CDFGHIKL:CGIDHFLK
CDFGHIJL:CGJDHFLI
CDFGHIJK:CGJDHFIK
CDEHIJKL:EJICHDLK
CDEGIJKL:EGICJDLK
CDEGHJKL:EGJCHDLK
CDEGHIKL:EGICHDLK
CDEGHIJL:EGJCHDLI
CDEGHIJK:EGJCHDIK
CDEFIJKL:CJEDIFLK
CDEFHJKL:CJEDHFLK
CDEFHIKL:CEIDHFLK
CDEFHIJL:CJEDHFLI
CDEFHIJK:CJEDHFIK
CDEFGJKL:CGEDJFLK
CDEFGIKL:CGEDIFLK
CDEFGIJL:CGEDJFLI
CDEFGIJK:CGEDJFIK
CDEFGHKL:CGEDHFLK
CDEFGHJL:CGJDHFLE
CDEFGHJK:CGJDHFEK
CDEFGHIL:CGEDHFLI
CDEFGHIK:CGEDHFIK
CDEFGHIJ:CGJDHFEI
BFGHIJKL:HJBFIGLK
BEGHIJKL:EJIBHGLK
BEFHIJKL:EJBFIHLK
BEFGIJKL:EJBFIGLK
BEFGHJKL:EJBFHGLK
BEFGHIKL:EGBFIHLK
BEFGHIJL:EJBFHGLI
BEFGHIJK:EJBFHGIK
BDGHIJKL:HJBDIGLK
BDFHIJKL:HJBDIFLK
BDFGIJKL:IGBDJFLK
BDFGHJKL:HGBDJFLK
BDFGHIKL:HGBDIFLK
BDFGHIJL:HGBDJFLI
BDFGHIJK:HGBDJFIK
BDEHIJKL:EJBDIHLK
BDEGIJKL:EJBDIGLK
BDEGHJKL:EJBDHGLK
BDEGHIKL:EGBDIHLK
BDEGHIJL:EJBDHGLI
BDEGHIJK:EJBDHGIK
BDEFIJKL:EJBDIFLK
BDEFHJKL:EJBDHFLK
BDEFHIKL:EIBDHFLK
BDEFHIJL:EJBDHFLI
BDEFHIJK:EJBDHFIK
BDEFGJKL:EGBDJFLK
BDEFGIKL:EGBDIFLK
BDEFGIJL:EGBDJFLI
BDEFGIJK:EGBDJFIK
BDEFGHKL:EGBDHFLK
BDEFGHJL:HGBDJFLE
BDEFGHJK:HGBDJFEK
BDEFGHIL:EGBDHFLI
BDEFGHIK:EGBDHFIK
BDEFGHIJ:HGBDJFEI
BCGHIJKL:HJBCIGLK
BCFHIJKL:HJBCIFLK
BCFGIJKL:IGBCJFLK
BCFGHJKL:HGBCJFLK
BCFGHIKL:HGBCIFLK
BCFGHIJL:HGBCJFLI
BCFGHIJK:HGBCJFIK
BCEHIJKL:EJBCIHLK
BCEGIJKL:EJBCIGLK
BCEGHJKL:EJBCHGLK
BCEGHIKL:EGBCIHLK
BCEGHIJL:EJBCHGLI
BCEGHIJK:EJBCHGIK
BCEFIJKL:EJBCIFLK
BCEFHJKL:EJBCHFLK
BCEFHIKL:EIBCHFLK
BCEFHIJL:EJBCHFLI
BCEFHIJK:EJBCHFIK
BCEFGJKL:EGBCJFLK
BCEFGIKL:EGBCIFLK
BCEFGIJL:EGBCJFLI
BCEFGIJK:EGBCJFIK
BCEFGHKL:EGBCHFLK
BCEFGHJL:HGBCJFLE
BCEFGHJK:HGBCJFEK
BCEFGHIL:EGBCHFLI
BCEFGHIK:EGBCHFIK
BCEFGHIJ:HGBCJFEI
BCDHIJKL:HJBCIDLK
BCDGIJKL:IGBCJDLK
BCDGHJKL:HGBCJDLK
BCDGHIKL:HGBCIDLK
BCDGHIJL:HGBCJDLI
BCDGHIJK:HGBCJDIK
BCDFIJKL:CJBDIFLK
BCDFHJKL:CJBDHFLK
BCDFHIKL:CIBDHFLK
BCDFHIJL:CJBDHFLI
BCDFHIJK:CJBDHFIK
BCDFGJKL:CGBDJFLK
BCDFGIKL:CGBDIFLK
BCDFGIJL:CGBDJFLI
BCDFGIJK:CGBDJFIK
BCDFGHKL:CGBDHFLK
BCDFGHJL:CGBDHFLJ
BCDFGHJK:HGBCJFDK
BCDFGHIL:CGBDHFLI
BCDFGHIK:CGBDHFIK
BCDFGHIJ:HGBCJFDI
BCDEIJKL:EJBCIDLK
BCDEHJKL:EJBCHDLK
BCDEHIKL:EIBCHDLK
BCDEHIJL:EJBCHDLI
BCDEHIJK:EJBCHDIK
BCDEGJKL:EGBCJDLK
BCDEGIKL:EGBCIDLK
BCDEGIJL:EGBCJDLI
BCDEGIJK:EGBCJDIK
BCDEGHKL:EGBCHDLK
BCDEGHJL:HGBCJDLE
BCDEGHJK:HGBCJDEK
BCDEGHIL:EGBCHDLI
BCDEGHIK:EGBCHDIK
BCDEGHIJ:HGBCJDEI
BCDEFJKL:CJBDEFLK
BCDEFIKL:CEBDIFLK
BCDEFIJL:CJBDEFLI
BCDEFIJK:CJBDEFIK
BCDEFHKL:CEBDHFLK
BCDEFHJL:CJBDHFLE
BCDEFHJK:CJBDHFEK
BCDEFHIL:CEBDHFLI
BCDEFHIK:CEBDHFIK
BCDEFHIJ:CJBDHFEI
BCDEFGKL:CGBDEFLK
BCDEFGJL:CGBDJFLE
BCDEFGJK:CGBDJFEK
BCDEFGIL:CGBDEFLI
BCDEFGIK:CGBDEFIK
BCDEFGIJ:CGBDJFEI
BCDEFGHL:CGBDHFLE
BCDEFGHK:CGBDHFEK
BCDEFGHJ:HGBCJFDE
BCDEFGHI:CGBDHFEI
AFGHIJKL:HJIFAGLK
AEGHIJKL:EJIAHGLK
AEFHIJKL:EJIFAHLK
AEFGIJKL:EJIFAGLK
AEFGHJKL:EGJFAHLK
AEFGHIKL:EGIFAHLK
AEFGHIJL:EGJFAHLI
AEFGHIJK:EGJFAHIK
ADGHIJKL:HJIDAGLK
ADFHIJKL:HJIDAFLK
ADFGIJKL:IGJDAFLK
ADFGHJKL:HGJDAFLK
ADFGHIKL:HGIDAFLK
ADFGHIJL:HGJDAFLI
ADFGHIJK:HGJDAFIK
ADEHIJKL:EJIDAHLK
ADEGIJKL:EJIDAGLK
ADEGHJKL:EGJDAHLK
ADEGHIKL:EGIDAHLK
ADEGHIJL:EGJDAHLI
ADEGHIJK:EGJDAHIK
ADEFIJKL:EJIDAFLK
ADEFHJKL:HJEDAFLK
ADEFHIKL:HEIDAFLK
ADEFHIJL:HJEDAFLI
ADEFHIJK:HJEDAFIK
ADEFGJKL:EGJDAFLK
ADEFGIKL:EGIDAFLK
ADEFGIJL:EGJDAFLI
ADEFGIJK:EGJDAFIK
ADEFGHKL:HGEDAFLK
ADEFGHJL:HGJDAFLE
ADEFGHJK:HGJDAFEK
ADEFGHIL:HGEDAFLI
ADEFGHIK:HGEDAFIK
ADEFGHIJ:HGJDAFEI
ACGHIJKL:HJICAGLK
ACFHIJKL:HJICAFLK
ACFGIJKL:IGJCAFLK
ACFGHJKL:HGJCAFLK
ACFGHIKL:HGICAFLK
ACFGHIJL:HGJCAFLI
ACFGHIJK:HGJCAFIK
ACEHIJKL:EJICAHLK
ACEGIJKL:EJICAGLK
ACEGHJKL:EGJCAHLK
ACEGHIKL:EGICAHLK
ACEGHIJL:EGJCAHLI
ACEGHIJK:EGJCAHIK
ACEFIJKL:EJICAFLK
ACEFHJKL:HJECAFLK
ACEFHIKL:HEICAFLK
ACEFHIJL:HJECAFLI
ACEFHIJK:HJECAFIK
ACEFGJKL:EGJCAFLK
ACEFGIKL:EGICAFLK
ACEFGIJL:EGJCAFLI
ACEFGIJK:EGJCAFIK
ACEFGHKL:HGECAFLK
ACEFGHJL:HGJCAFLE
ACEFGHJK:HGJCAFEK
ACEFGHIL:HGECAFLI
ACEFGHIK:HGECAFIK
ACEFGHIJ:HGJCAFEI
ACDHIJKL:HJICADLK
ACDGIJKL:IGJCADLK
ACDGHJKL:HGJCADLK
ACDGHIKL:HGICADLK
ACDGHIJL:HGJCADLI
ACDGHIJK:HGJCADIK
ACDFIJKL:CJIDAFLK
ACDFHJKL:HJFCADLK
ACDFHIKL:HFICADLK
ACDFHIJL:HJFCADLI
ACDFHIJK:HJFCADIK
ACDFGJKL:CGJDAFLK
ACDFGIKL:CGIDAFLK
ACDFGIJL:CGJDAFLI
ACDFGIJK:CGJDAFIK
ACDFGHKL:HGFCADLK
ACDFGHJL:CGJDAFLH
ACDFGHJK:HGJCAFDK
ACDFGHIL:HGFCADLI
ACDFGHIK:HGFCADIK
ACDFGHIJ:HGJCAFDI
ACDEIJKL:EJICADLK
ACDEHJKL:HJECADLK
ACDEHIKL:HEICADLK
ACDEHIJL:HJECADLI
ACDEHIJK:HJECADIK
ACDEGJKL:EGJCADLK
ACDEGIKL:EGICADLK
ACDEGIJL:EGJCADLI
ACDEGIJK:EGJCADIK
ACDEGHKL:HGECADLK
ACDEGHJL:HGJCADLE
ACDEGHJK:HGJCADEK
ACDEGHIL:HGECADLI
ACDEGHIK:HGECADIK
ACDEGHIJ:HGJCADEI
ACDEFJKL:CJEDAFLK
ACDEFIKL:CEIDAFLK
ACDEFIJL:CJEDAFLI
ACDEFIJK:CJEDAFIK
ACDEFHKL:HEFCADLK
ACDEFHJL:HJFCADLE
ACDEFHJK:HJECAFDK
ACDEFHIL:HEFCADLI
ACDEFHIK:HEFCADIK
ACDEFHIJ:HJECAFDI
ACDEFGKL:CGEDAFLK
ACDEFGJL:CGJDAFLE
ACDEFGJK:CGJDAFEK
ACDEFGIL:CGEDAFLI
ACDEFGIK:CGEDAFIK
ACDEFGIJ:CGJDAFEI
ACDEFGHL:HGFCADLE
ACDEFGHK:HGECAFDK
ACDEFGHJ:HGJCAFDE
ACDEFGHI:HGECAFDI
ABGHIJKL:HJBAIGLK
ABFHIJKL:HJBAIFLK
ABFGIJKL:IJBFAGLK
ABFGHJKL:HJBFAGLK
ABFGHIKL:HGBAIFLK
ABFGHIJL:HJBFAGLI
ABFGHIJK:HJBFAGIK
ABEHIJKL:EJBAIHLK
ABEGIJKL:EJBAIGLK
ABEGHJKL:EJBAHGLK
ABEGHIKL:EGBAIHLK
ABEGHIJL:EJBAHGLI
ABEGHIJK:EJBAHGIK
ABEFIJKL:EJBAIFLK
ABEFHJKL:EJBFAHLK
ABEFHIKL:EIBFAHLK
ABEFHIJL:EJBFAHLI
ABEFHIJK:EJBFAHIK
ABEFGJKL:EJBFAGLK
ABEFGIKL:EGBAIFLK
ABEFGIJL:EJBFAGLI
ABEFGIJK:EJBFAGIK
ABEFGHKL:EGBFAHLK
ABEFGHJL:HJBFAGLE
ABEFGHJK:HJBFAGEK
ABEFGHIL:EGBFAHLI
ABEFGHIK:EGBFAHIK
ABEFGHIJ:HJBFAGEI
ABDHIJKL:IJBDAHLK
ABDGIJKL:IJBDAGLK
ABDGHJKL:HJBDAGLK
ABDGHIKL:IGBDAHLK
ABDGHIJL:HJBDAGLI
ABDGHIJK:HJBDAGIK
ABDFIJKL:IJBDAFLK
ABDFHJKL:HJBDAFLK
ABDFHIKL:HIBDAFLK
ABDFHIJL:HJBDAFLI
ABDFHIJK:HJBDAFIK
ABDFGJKL:FJBDAGLK
ABDFGIKL:IGBDAFLK
ABDFGIJL:FJBDAGLI
ABDFGIJK:FJBDAGIK
ABDFGHKL:HGBDAFLK
ABDFGHJL:HGBDAFLJ
ABDFGHJK:HGBDAFJK
ABDFGHIL:HGBDAFLI
ABDFGHIK:HGBDAFIK
ABDFGHIJ:HGBDAFIJ
ABDEIJKL:EJBAIDLK
ABDEHJKL:EJBDAHLK
ABDEHIKL:EIBDAHLK
ABDEHIJL:EJBDAHLI
ABDEHIJK:EJBDAHIK
ABDEGJKL:EJBDAGLK
ABDEGIKL:EGBAIDLK
ABDEGIJL:EJBDAGLI
ABDEGIJK:EJBDAGIK
ABDEGHKL:EGBDAHLK
ABDEGHJL:HJBDAGLE
ABDEGHJK:HJBDAGEK
ABDEGHIL:EGBDAHLI
ABDEGHIK:EGBDAHIK
ABDEGHIJ:HJBDAGEI
ABDEFJKL:EJBDAFLK
ABDEFIKL:EIBDAFLK
ABDEFIJL:EJBDAFLI
ABDEFIJK:EJBDAFIK
ABDEFHKL:HEBDAFLK
ABDEFHJL:HJBDAFLE
ABDEFHJK:HJBDAFEK
ABDEFHIL:HEBDAFLI
ABDEFHIK:HEBDAFIK
ABDEFHIJ:HJBDAFEI
ABDEFGKL:EGBDAFLK
ABDEFGJL:EGBDAFLJ
ABDEFGJK:EGBDAFJK
ABDEFGIL:EGBDAFLI
ABDEFGIK:EGBDAFIK
ABDEFGIJ:EGBDAFIJ
ABDEFGHL:HGBDAFLE
ABDEFGHK:HGBDAFEK
ABDEFGHJ:HGBDAFEJ
ABDEFGHI:HGBDAFEI
ABCHIJKL:IJBCAHLK
ABCGIJKL:IJBCAGLK
ABCGHJKL:HJBCAGLK
ABCGHIKL:IGBCAHLK
ABCGHIJL:HJBCAGLI
ABCGHIJK:HJBCAGIK
ABCFIJKL:IJBCAFLK
ABCFHJKL:HJBCAFLK
ABCFHIKL:HIBCAFLK
ABCFHIJL:HJBCAFLI
ABCFHIJK:HJBCAFIK
ABCFGJKL:CJBFAGLK
ABCFGIKL:IGBCAFLK
ABCFGIJL:CJBFAGLI
ABCFGIJK:CJBFAGIK
ABCFGHKL:HGBCAFLK
ABCFGHJL:HGBCAFLJ
ABCFGHJK:HGBCAFJK
ABCFGHIL:HGBCAFLI
ABCFGHIK:HGBCAFIK
ABCFGHIJ:HGBCAFIJ
ABCEIJKL:EJBAICLK
ABCEHJKL:EJBCAHLK
ABCEHIKL:EIBCAHLK
ABCEHIJL:EJBCAHLI
ABCEHIJK:EJBCAHIK
ABCEGJKL:EJBCAGLK
ABCEGIKL:EGBAICLK
ABCEGIJL:EJBCAGLI
ABCEGIJK:EJBCAGIK
ABCEGHKL:EGBCAHLK
ABCEGHJL:HJBCAGLE
ABCEGHJK:HJBCAGEK
ABCEGHIL:EGBCAHLI
ABCEGHIK:EGBCAHIK
ABCEGHIJ:HJBCAGEI
ABCEFJKL:EJBCAFLK
ABCEFIKL:EIBCAFLK
ABCEFIJL:EJBCAFLI
ABCEFIJK:EJBCAFIK
ABCEFHKL:HEBCAFLK
ABCEFHJL:HJBCAFLE
ABCEFHJK:HJBCAFEK
ABCEFHIL:HEBCAFLI
ABCEFHIK:HEBCAFIK
ABCEFHIJ:HJBCAFEI
ABCEFGKL:EGBCAFLK
ABCEFGJL:EGBCAFLJ
ABCEFGJK:EGBCAFJK
ABCEFGIL:EGBCAFLI
ABCEFGIK:EGBCAFIK
ABCEFGIJ:EGBCAFIJ
ABCEFGHL:HGBCAFLE
ABCEFGHK:HGBCAFEK
ABCEFGHJ:HGBCAFEJ
ABCEFGHI:HGBCAFEI
ABCDIJKL:IJBCADLK
ABCDHJKL:HJBCADLK
ABCDHIKL:HIBCADLK
ABCDHIJL:HJBCADLI
ABCDHIJK:HJBCADIK
ABCDGJKL:CJBDAGLK
ABCDGIKL:IGBCADLK
ABCDGIJL:CJBDAGLI
ABCDGIJK:CJBDAGIK
ABCDGHKL:HGBCADLK
ABCDGHJL:HGBCADLJ
ABCDGHJK:HGBCADJK
ABCDGHIL:HGBCADLI
ABCDGHIK:HGBCADIK
ABCDGHIJ:HGBCADIJ
ABCDFJKL:CJBDAFLK
ABCDFIKL:CIBDAFLK
ABCDFIJL:CJBDAFLI
ABCDFIJK:CJBDAFIK
ABCDFHKL:HFBCADLK
ABCDFHJL:CJBDAFLH
ABCDFHJK:HJBCAFDK
ABCDFHIL:HFBCADLI
ABCDFHIK:HFBCADIK
ABCDFHIJ:HJBCAFDI
ABCDFGKL:CGBDAFLK
ABCDFGJL:CGBDAFLJ
ABCDFGJK:CGBDAFJK
ABCDFGIL:CGBDAFLI
ABCDFGIK:CGBDAFIK
ABCDFGIJ:CGBDAFIJ
ABCDFGHL:CGBDAFLH
ABCDFGHK:HGBCAFDK
ABCDFGHJ:HGBCAFDJ
ABCDFGHI:HGBCAFDI
ABCDEJKL:EJBCADLK
ABCDEIKL:EIBCADLK
ABCDEIJL:EJBCADLI
ABCDEIJK:EJBCADIK
ABCDEHKL:HEBCADLK
ABCDEHJL:HJBCADLE
ABCDEHJK:HJBCADEK
ABCDEHIL:HEBCADLI
ABCDEHIK:HEBCADIK
ABCDEHIJ:HJBCADEI
ABCDEGKL:EGBCADLK
ABCDEGJL:EGBCADLJ
ABCDEGJK:EGBCADJK
ABCDEGIL:EGBCADLI
ABCDEGIK:EGBCADIK
ABCDEGIJ:EGBCADIJ
ABCDEGHL:HGBCADLE
ABCDEGHK:HGBCADEK
ABCDEGHJ:HGBCADEJ
ABCDEGHI:HGBCADEI
ABCDEFKL:CEBDAFLK
ABCDEFJL:CJBDAFLE
ABCDEFJK:CJBDAFEK
ABCDEFIL:CEBDAFLI
ABCDEFIK:CEBDAFIK
ABCDEFIJ:CJBDAFEI
ABCDEFHL:HFBCADLE
ABCDEFHK:HEBCAFDK
ABCDEFHJ:HJBCAFDE
ABCDEFHI:HEBCAFDI
ABCDEFGL:CGBDAFLE
ABCDEFGK:CGBDAFEK
ABCDEFGJ:CGBDAFEJ
ABCDEFGI:CGBDAFEI
ABCDEFGH:HGBCAFDE`;

const ANNEX_C = new Map();
for (const line of ANNEX_C_RAW.trim().split("\n")) {
  const [qualifying, assignment] = line.split(":");
  const map = {};
  SLOT_COLS.forEach((col, i) => (map[col] = assignment[i]));
  ANNEX_C.set(qualifying, map);
}

/**
 * Given the 8 group letters whose third-place team qualified (any order),
 * returns { A, B, D, E, G, I, K, L } mapping each "3rd place" bracket slot
 * to the group letter whose third-place team fills it. Returns null if the
 * input isn't a valid set of exactly 8 distinct group letters.
 */
export function resolveThirdPlaceSlots(qualifyingGroupLetters) {
  if (!qualifyingGroupLetters || qualifyingGroupLetters.length !== 8) return null;
  const key = [...qualifyingGroupLetters].sort().join("");
  return ANNEX_C.get(key) || null;
}
